/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.ufrsciencestech.panier.view;

import fr.ufrsciencestech.panier.controler.Controleur;
import java.util.Observable;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author ch098407
 */
public class VueGSwing extends javax.swing.JFrame implements VueG{

    /**
     * Creates new form vuePanier
     */
    public VueGSwing() {
        initComponents();
        //this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LOrange = new javax.swing.JLabel();
        BtAjouterOrange = new javax.swing.JButton();
        BtRetirerOrange = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LOrange.setText("Nombre d'orange");

        BtAjouterOrange.setText("Ajouter une Orange");
        BtAjouterOrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAjouterOrangeActionPerformed(evt);
            }
        });

        BtRetirerOrange.setText("Retirer une orange");
        BtRetirerOrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtRetirerOrangeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtAjouterOrange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(LOrange, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(280, Short.MAX_VALUE))
            .addComponent(BtRetirerOrange, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BtAjouterOrange)
                .addGap(27, 27, 27)
                .addComponent(LOrange, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtRetirerOrange))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtAjouterOrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAjouterOrangeActionPerformed
        
    }//GEN-LAST:event_BtAjouterOrangeActionPerformed

    private void BtRetirerOrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRetirerOrangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtRetirerOrangeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueGSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueGSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueGSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueGSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VueGSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAjouterOrange;
    private javax.swing.JButton BtRetirerOrange;
    private javax.swing.JLabel LOrange;
    // End of variables declaration//GEN-END:variables

    
    public JLabel getAffiche() {
        return LOrange;
    }
    @Override
    public void update(Observable m, Object compte){     //Appellé à chaque fois que l'objet modifié change
        getAffiche().setText(((Integer) compte).toString());
    }

    @Override
    public void addControleur(Controleur c) {
        BtAjouterOrange.addActionListener(c);
        getBtRetirer().addActionListener(c);
    }
    
    /**
     * @return le bouton BtAjouterOrange
     */
    public JButton getBtAjouter() {
        return BtAjouterOrange;
    }

    /**
     * @param btAjouter le BtAjouterOrange à btAjouter
     */
    public void setBtAjouter(JButton btAjouter) {
        this.BtAjouterOrange = btAjouter;
    }

    /**
     * @return le bouton retirer
     */
    public JButton getBtRetirer() {
        return BtRetirerOrange;
    }

    /**
     * @param btRetirer le BtRetirerOrange à btRetirer
     */
    public void setBtRetirer(JButton btRetirer) {
        this.BtRetirerOrange = btRetirer;
    }
    

    /**
     * @param lOrange le LOrange à lOrange
     */
    public void setAffiche(JLabel lOrange) {
        this.LOrange = lOrange;
    }
}
